football/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "football"
urlpatterns = [
    path('rule/', views.rule, name='rule'),
    path('predict/', views.predict, name='predict'),
    path('result/', views.ResultView.as_view(), name='result'),
    path('user/', views.user, name='user'),
    url(r'^(?P<data_id>[0-9]+)/vote/$', views.VoteView.as_view(), name='vote'),
    url(r'^(?P<data_id>[0-9]+)/reference/$', views.reference, name='reference'),
    url(r'^', views.HomeView.as_view(), name='home'),
]

mysite/urls.py
from django.contrib.auth import views
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^', include('football.urls')),
]

football/models.py
from django.forms.widgets import HiddenInput
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.forms import ModelForm


class Schedule(models.Model):
    level1="1-32"
    level2="1-16"
    level3="Quarterfinal"
    level4="Semifinal"
    level5="Third place"
    level6="Final"
    level_choises = (
        (level1, 'Vòng bảng'),
        (level2, 'Vòng 1-16'),
        (level3, 'Tứ kết'),
        (level4, 'Bán kết'),
        (level5, 'Giải ba'),
        (level6, 'Chung kết')
    )
    none = -1
    zero = 0
    one = 1
    two = 2
    three = 3
    four = 4
    five = 5
    six = 6
    seven = 7
    eight = 8
    nine = 9
    ten = 10
    eleven = 11
    twelfth = 12
    thirteen = 13
    fourteen = 14
    fifteen = 15
    sixteen = 16
    seventeen = 17
    eighteen = 18
    nineteen = 19
    twenty = 20
    Score_choises = (
        (none, 'Chưa thi đấu'),
        (zero, '0'),
        (one, '1'),
        (two, '2'),
        (three, '3'),
        (four, '4'),
        (five, '5'),
        (six, '6'),
        (seven, '7'),
        (eight, '8'),
        (nine, '9'),
        (ten, '10'),
        (eleven, '11'),
        (twelfth, '12'),
        (thirteen, '13'),
        (fourteen, '14'),
        (fifteen, '15'),
        (sixteen, '16'),
        (seventeen, '17'),
        (eighteen, '18'),
        (nineteen, '19'),
        (twenty, '20')
    )
    match_date = models.DateTimeField(default=datetime.now())
    team_a = models.CharField(max_length=200)
    team_b = models.CharField(max_length=200)
    level = models.CharField(max_length=200, choices=level_choises, default=level1)
    score_a = models.IntegerField(choices=Score_choises, default=none)
    score_b = models.IntegerField(choices=Score_choises, default=none)
    result_point = models.IntegerField(default=1)
    score_point = models.IntegerField(default=5)


class Data(models.Model):
    AWIN = 'AWIN'
    BALANCE = 'BALANCE'
    BWIN = 'BWIN'
    NEW = '-'
    RESULT_CHOICES = (
        (AWIN, 'Đội A thắng'),
        (BALANCE, 'Hai đội hòa'),
        (BWIN, 'Đội B thắng'),
        (NEW, '-')
    )
    none = -1
    zero = 0
    one = 1
    two = 2
    three = 3
    four = 4
    five = 5
    six = 6
    seven = 7
    eight = 8
    nine = 9
    ten = 10
    eleven = 11
    twelfth = 12
    thirteen = 13
    fourteen = 14
    fifteen = 15
    sixteen = 16
    seventeen = 17
    eighteen = 18
    nineteen = 19
    twenty = 20
    Score_choises = (
        (none, 'Không chọn'),
        (zero, '0'),
        (one, '1'),
        (two, '2'),
        (three, '3'),
        (four, '4'),
        (five, '5'),
        (six, '6'),
        (seven, '7'),
        (eight, '8'),
        (nine, '9'),
        (ten, '10'),
        (eleven, '11'),
        (twelfth, '12'),
        (thirteen, '13'),
        (fourteen, '14'),
        (fifteen, '15'),
        (sixteen, '16'),
        (seventeen, '17'),
        (eighteen, '18'),
        (nineteen, '19'),
        (twenty, '20')
    )
    user_data = models.ForeignKey(User, on_delete=models.CASCADE)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    predict_winner = models.CharField(max_length=200, choices=RESULT_CHOICES, default=NEW)
    winner_result = models.BooleanField(default=False)
    predict_score_a = models.IntegerField(choices=Score_choises, default=none)
    predict_score_b = models.IntegerField(choices=Score_choises, default=none)
    score_result = models.BooleanField(default=False)
    reward = models.IntegerField(default=0)


class Summary(models.Model):
    user_data = models.ForeignKey(User, on_delete=models.CASCADE)
    winner_number = models.IntegerField(default=0)
    winner_point = models.IntegerField(default=0)
    score_number = models.IntegerField(default=0)
    score_point = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    total_reward = models.IntegerField(default=0)


class DataForm(ModelForm):
    class Meta:
        model = Data
        fields = [ 'user_data', 'schedule', 'predict_winner', 'predict_score_a', 'predict_score_b']
        widgets = {
            'user_data': HiddenInput(),
            'schedule': HiddenInput(),
        }

football/views.py
from datetime import datetime
from django.db.models.functions import Lower
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from football.models import Data, Summary, DataForm
from django.views.generic.edit import UpdateView


class HomeView(generic.ListView):
    template_name = 'football/home.html'
    context_object_name = 'summary'

    def get_queryset(self):
        return Summary.objects.all().order_by(Lower('total').desc())


def predict(request):
        template = loader.get_template('football/predict.html')
        try:
            datas = Data.objects.filter(user_data__username=request.user,schedule__match_date__gt=datetime.now())
            context = {
                'datas': datas,
            }
            return HttpResponse(template.render(context, request))
        except Data.DoesNotExist:
            return render(request, 'football/nodata.html')


class VoteView(UpdateView):
    form_class = DataForm
    model = Data
    template_name = 'football/vote.html'
    success_url = '/predict/'

    def get_object(self, queryset=None):
        obj = Data.objects.get(id=self.kwargs['data_id'],schedule__match_date__gt=datetime.now())
        return obj

def reference(request, data_id):
    data = get_object_or_404(Data, pk=data_id)
    userdatas=Data.objects.filter(schedule=data.schedule)
    template = loader.get_template('football/reference.html')
    context = {
        'userdatas': userdatas,
    }
    return HttpResponse(template.render(context, request))

class ResultView(generic.ListView):
    template_name = 'football/result.html'
    context_object_name = 'user_data'

    def get_queryset(self):
        return Data.objects.filter(user_data__username=self.request.user)

def rule(request):
    return render(request, 'football/rule.html')

def user(request):
    return render(request, 'football/user.html')

templates/football/home.html
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>Dự đoán kết quả bóng đá</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .center {
  padding: 40px 0;
  font-size: 25px;
  text-align: center;
  color: red;
  }
  </style>
  {% load sum_reward %}
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
     <ul class="nav navbar-nav">
        <li><a href="{% url 'football:home' %}"><span class="glyphicon glyphicon-home"></span> Trang chủ</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:predict' %}"><span class="glyphicon glyphicon-edit"></span> Dự đoán</a></li>
        <li><a href="{% url 'football:result' %}"><span class="glyphicon glyphicon-star"></span> Bảng điểm</a></li>
        {% endif %}
        <li><a href="{% url 'football:rule' %}"><span class="glyphicon glyphicon-question-sign"></span> Luật chơi</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:user' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-cog"></span>  Đổi mật khẩu</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Đăng xuất</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>  Đăng nhập</a></li>
        {% endif %}
     </ul>
  </div>
</nav>

<div class="container">
  <div class="center">
     <p>Giải thưởng</p>
     <p>{{ summary|running_total }}$</p>
  </div>
  <table class="table table-hover">
     <thead>
        <tr class="info">
            <th width="12%">Tài khoản</th>
            <th width="22%">Dự đoán kết quả</th>
            <th width="22%">Dự đoán tỉ số</th>
            <th width="22%">Tổng số lần đúng</th>
            <th width="22%">Tổng số tiền</th>
        </tr>
     </thead>
     <tbody>
     {% for sumuser in summary %}
        <tr class="active">
            <th>{{ sumuser.user_data.username }}</th>
            <th>Đúng: {{ sumuser.winner_number }} | Tiền: {{ sumuser.winner_point }}$</th>
            <th>Đúng: {{ sumuser.score_number }} | Tiền: {{ sumuser.score_point }}$</th>
            <th>{{ sumuser.total }}</th>
            <th>{{ sumuser.total_reward }}$</th>
        </tr>
     {% endfor %}
     </tbody>
  </table>
</div>
</body>
</html>

templates/football/nodata.html
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>Dự đoán kết quả bóng đá</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .center {
  padding: 200px 0;
  font-size: 20px;
  text-align: center;
  }
  </style>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
     <ul class="nav navbar-nav">
        <li><a href="{% url 'football:home' %}"><span class="glyphicon glyphicon-home"></span> Trang chủ</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:predict' %}"><span class="glyphicon glyphicon-edit"></span> Dự đoán</a></li>
        <li><a href="{% url 'football:result' %}"><span class="glyphicon glyphicon-star"></span> Bảng điểm</a></li>
        {% endif %}
        <li><a href="{% url 'football:rule' %}"><span class="glyphicon glyphicon-question-sign"></span> Luật chơi</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:user' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-cog"></span>  Đổi mật khẩu</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Đăng xuất</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>  Đăng nhập</a></li>
        {% endif %}
     </ul>
  </div>
</nav>

<div class="container">
  <div class="center">
     <p>Không còn trận nào chưa thi đấu</p>
  </div>

</div>
</body>
</html>

templates/football/predict.html
<!DOCTYPE html>
<html lang="vi">
{% if user.is_authenticated %}
<head>
  <title>Dự đoán kết quả bóng đá</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
     <ul class="nav navbar-nav">
        <li><a href="{% url 'football:home' %}"><span class="glyphicon glyphicon-home"></span> Trang chủ</a></li>
        <li><a href="{% url 'football:predict' %}"><span class="glyphicon glyphicon-edit"></span> Dự đoán</a></li>
        <li><a href="{% url 'football:result' %}"><span class="glyphicon glyphicon-star"></span> Bảng điểm</a></li>
        <li><a href="{% url 'football:rule' %}"><span class="glyphicon glyphicon-question-sign"></span> Luật chơi</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'football:user' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-cog"></span>  Đổi mật khẩu</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Đăng xuất</a></li>
     </ul>
  </div>
</nav>

<div class="container">
  <table class="table table-hover">
     <thead>
        <tr class="info">
            <th width="20%">Thời gian</th>
            <th width="20%">Trận đấu</th>
            <th width="20%">Vòng đấu</th>
            <th width="20%">Tham gia dự đoán</th>
            <th width="20%">Thông tin tham khảo</th>
        </tr>
     </thead>
     <tbody>
        {% for data in datas %}
        <tr class="active">
            <th>{{ data.schedule.match_date|date:"H:i dMY"}}</th>
            <th>{{ data.schedule.team_a}} - {{ data.schedule.team_b}}</th>
            {% if data.schedule.level == "1-32" %}
                <th>Vòng bảng</th>
            {% endif %}
            {% if data.schedule.level == "1-16" %}
                <th>Vòng 1-16</th>
            {% endif %}
            {% if data.schedule.level == "Quarterfinal" %}
                <th>Tứ kết</th>
            {% endif %}
            {% if data.schedule.level == "Semifinal" %}
                <th>Bán kết</th>
            {% endif %}
            {% if data.schedule.level == "Third place" %}
                <th>Tranh giải ba</th>
            {% endif %}
            {% if data.schedule.level == "Final" %}
                <th>Chung kết</th>
            {% endif %}
            <th><a href="{% url 'football:vote' data.id %}">Dự đoán</a></th>
            <th><a href="{% url 'football:reference' data.id %}">Tham khảo</a></th>
        </tr>
        {% endfor %}
     </tbody>
  </table>
</div>

</body>
{% else %}
<head>
<style>
.center {
  padding: 200px 0;
  font-size: 25px;
  text-align: center;
}
</style>
</head>
<body>
<div class="center">
   <p><a href="{% url 'login' %}">Đăng nhập</a></p>
</div>
</body>
{% endif %}
</html>

templates/football/reference.html
<!DOCTYPE html>
<html lang="vi">
{% if user.is_authenticated %}
<head>
  <title>Dự đoán kết quả bóng đá</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
     <ul class="nav navbar-nav">
        <li><a href="{% url 'football:home' %}"><span class="glyphicon glyphicon-home"></span> Trang chủ</a></li>
        <li><a href="{% url 'football:predict' %}"><span class="glyphicon glyphicon-edit"></span> Dự đoán</a></li>
        <li><a href="{% url 'football:result' %}"><span class="glyphicon glyphicon-star"></span> Bảng điểm</a></li>
        <li><a href="{% url 'football:rule' %}"><span class="glyphicon glyphicon-question-sign"></span> Luật chơi</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'football:user' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-cog"></span>  Đổi mật khẩu</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Đăng xuất</a></li>
     </ul>
  </div>
</nav>

<div class="container">
  <table class="table table-hover">
     <thead>
        <tr class="info">
            <th width="16%">Thời gian</th>
            <th width="20%">Trận đấu</th>
            <th width="16%">Vòng đấu</th>
            <th width="16%">Tài khoản</th>
            <th width="16%">Dự đoán kết quả</th>
            <th width="16%">Dự đoán tỉ số</th>
        </tr>
     </thead>
     <tbody>
     {% for userdata in userdatas %}
        <tr class="active">
            <th>{{ userdata.schedule.match_date|date:"H:i dMY"}}</th>
            <th>{{ userdata.schedule.team_a}} - {{ userdata.schedule.team_b}}</th>
            {% if userdata.schedule.level == "1-32" %}
                <th>Vòng bảng</th>
            {% endif %}
            {% if userdata.schedule.level == "1-16" %}
                <th>Vòng 1-16</th>
            {% endif %}
            {% if userdata.schedule.level == "Quarterfinal" %}
                <th>Tứ kết</th>
            {% endif %}
            {% if userdata.schedule.level == "Semifinal" %}
                <th>Bán kết</th>
            {% endif %}
            {% if data.schedule.level == "Third place" %}
                <th>Tranh giải ba</th>
            {% endif %}
            {% if userdata.schedule.level == "Final" %}
                <th>Chung kết</th>
            {% endif %}
            <th>{{ userdata.user_data.username}}</th>
            {% if userdata.predict_winner == "AWIN" %}
                <th>{{userdata.schedule.team_a}} thắng</th>
            {% else %}
                {% if userdata.predict_winner == "BWIN" %}
                    <th>{{userdata.schedule.team_b}} thắng</th>
                {% else %}
                    {% if userdata.predict_winner == "BALANCE" %}
                        <th>Hai đội hòa</th>
                    {% else %}
                        <th>-</th>
                    {% endif %}
                {%  endif %}
            {% endif %}
            <th>{% if userdata.predict_score_a > -1 %}
                    {% if userdata.predict_score_b > -1 %}
                        {{ userdata.predict_score_a}} - {{userdata.predict_score_b}}
                    {% else %}
                        -
                    {% endif %}
                {% else %}
                     -
                {% endif %}
            </th>
        </tr>
     {% endfor %}
     </tbody>
  </table>
</div>

</body>
{% else %}
<head>
<style>
.center {
  padding: 200px 0;
  font-size: 25px;
  text-align: center;
}
</style>
</head>
<body>
<div class="center">
   <p><a href="{% url 'login' %}">Đăng nhập</a></p>
</div>
</body>
{% endif %}
</html>

templates/football/result.html
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>Dự đoán kết quả bóng đá</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <style>
  .center {
  padding: 200px 0;
  font-size: 20px;
  text-align: center;
  }
  </style>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
     <ul class="nav navbar-nav">
        <li><a href="{% url 'football:home' %}"><span class="glyphicon glyphicon-home"></span> Trang chủ</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:predict' %}"><span class="glyphicon glyphicon-edit"></span> Dự đoán</a></li>
        <li><a href="{% url 'football:result' %}"><span class="glyphicon glyphicon-star"></span> Bảng điểm</a></li>
        {% endif %}
        <li><a href="{% url 'football:rule' %}"><span class="glyphicon glyphicon-question-sign"></span> Luật chơi</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:user' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-cog"></span>  Đổi mật khẩu</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Đăng xuất</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>  Đăng nhập</a></li>
        {% endif %}
     </ul>
  </div>
</nav>

<div class="container">
{% if user_data %}
   <table class="table table-hover">
   <thead>
      <tr class="info">
          <th width="16%">Thời gian</th>
          <th width="20%">Trận đấu</th>
          <th width="16%">Tỉ số trận đấu</th>
          <th width="16%">Dự đoán kết quả</th>
          <th width="16%">Dự đoán tỉ số</th>
          <th width="16%">Tổng số tiền</th>
      </tr>
   </thead>
   <tbody>
   {% for data in user_data %}
      <tr class="active">
          <th>{{data.schedule.match_date|date:"H:i dMY"}}</th>
          <th>{{data.schedule.team_a}} - {{data.schedule.team_b}}</th>
          {% if data.schedule.score_a > -1 %}
              {% if data.schedule.score_b > -1 %}
              <th>{{data.schedule.score_a}} : {{data.schedule.score_b}}</th>
              {% else %}
              <th>-</th>
              {% endif %}
          {% else %}
          <th>-</th>
          {% endif %}
          {% if data.predict_winner == "AWIN" %}
              <th>{{data.schedule.team_a}} thắng</th>
          {% else %}
              {% if data.predict_winner == "BWIN" %}
              <th>{{data.schedule.team_b}} thắng</th>
              {% else %}
                  {% if data.predict_winner == "BALANCE" %}
                  <th>Hai đội hòa</th>
                  {% else %}
                  <th>-</th>
                  {% endif %}
              {% endif %}
          {% endif %}
          {% if data.predict_score_a > -1 %}
              {% if data.predict_score_b > -1 %}
                  <th>{{data.predict_score_a}} : {{data.predict_score_b}}</th>
              {% else %}
                  <th>-</th>
              {% endif %}
          {% else %}
              <th>-</th>
          {%  endif %}
          <th>{{data.reward}}$</th>
      </tr>
   {% endfor %}
   </tbody>
</table>
{% else %}
   <div class="center">
       <p>Không có dữ liệu trận đấu</p>
   </div>
{% endif %}
</div>
</body>
</html>

templates/football/user.html
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>Dự đoán kết quả bóng đá</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <style>
  .center {
  padding: 200px 0;
  font-size: 20px;
  text-align: center;
  }
  </style>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
     <ul class="nav navbar-nav">
        <li><a href="{% url 'football:home' %}"><span class="glyphicon glyphicon-home"></span> Trang chủ</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:predict' %}"><span class="glyphicon glyphicon-edit"></span> Dự đoán</a></li>
        <li><a href="{% url 'football:result' %}"><span class="glyphicon glyphicon-star"></span> Bảng điểm</a></li>
        {% endif %}
        <li><a href="{% url 'football:rule' %}"><span class="glyphicon glyphicon-question-sign"></span> Luật chơi</a></li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'football:user' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.username }}</a></li>
        <li><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-cog"></span>  Đổi mật khẩu</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>  Đăng xuất</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>  Đăng nhập</a></li>
        {% endif %}
     </ul>
  </div>
</nav>

<div class="container">
{% if user.is_authenticated %}
   <table class="table table-hover">
   <thead>
      <tr class="info">
          <th width="16%">User Name</th>
          <th width="16%">First Name</th>
          <th width="16%">Last Name</th>
          <th width="20%">Email</th>
          <th width="16%">Last Login</th>
          <th width="16%">Date Joined</th>
      </tr>
   </thead>
   <tbody>
      <tr class="active">
          <th>{{user.username}}</th>
          <th>{{user.first_name}}</th>
          <th>{{user.last_name }}</th>
          <th>{{user.email}}</th>
          <th>{{user.last_login|date:"H:i dMY"}}</th>
          <th>{{user.date_joined|date:"H:i dMY"}}</th>
      </tr>
   </tbody>
</table>
{% endif %}
</div>
</body>
</html>